## Bruke NumPy

Når du har installert NumPy, kan du importere det som et bibliotek:

In [1]:
import numpy as np

c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


NumPy har mange innebygde funksjoner og muligheter. Vi vil ikke dekke dem alle, men i stedet vil vi fokusere på noen av de viktigste aspektene ved NumPy: vektorer, matriser, matriser og tallgenerering. La oss starte med å lære om matriser.

# Numpy Arrays

NumPy arrays er den viktigste måten vi vil bruke Numpy gjennom hele kurset. Numpy arrays kommer i hovedsak i to fasonger: vektorer og matriser. Vektorer er strengt tatt 1-d-matriser og matriser er 2-d (men du må være oppmerksom på at en matrise fortsatt kan ha bare en rad eller en kolonne).

La oss begynne introduksjonen med å utforske hvordan du lager NumPy-arrays.

## Opprette NumPy Arrays

### Fra en Python-liste

Vi kan opprette en matrise ved å konvertere en liste eller en liste over lister direkte:

[1, 2, 3]

array([1, 2, 3])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Innebygde metoder

Det er mange innebygde måter å generere arrays på

### arange

Returner jevnt fordelte verdier innenfor et gitt intervall.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10])

### zeroes og ones

Generer matriser med nuller eller enere.

array([0., 0., 0.])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([1., 1., 1.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Returner jevnt fordelte tall over et spesifisert intervall.

array([ 0.,  5., 10.])

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Oppretter en identitetsmatrise.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Tilfeldig 

NumPy har også mange måter å lage tilfeldige tallmatriser:

### rand
Lager en matrise av den gitte formen og fyll den ut med
tilfeldige prøver fra en jevn fordeling
over ``[0, 1)``.

array([0.40883214, 0.56743839])

array([[0.87660652, 0.23028965, 0.28607064, 0.31143579, 0.49866078],
       [0.78354541, 0.06360526, 0.25016668, 0.12600765, 0.80499342],
       [0.07608308, 0.00834786, 0.63953816, 0.65268712, 0.91716509],
       [0.94284278, 0.74403933, 0.92184904, 0.84423764, 0.25095705],
       [0.92805026, 0.85510419, 0.4149698 , 0.78617211, 0.92195993]])

### randn

Returner en sample (eller sampler) fra "standard normal" -fordelingen. I motsetning til rand som er ensartet:

array([-0.41174453, -0.9259137 ])

array([[-0.4866678 ,  0.94806029,  1.93708408, -0.58563676,  0.96100338],
       [-0.89524403,  0.252576  ,  0.0231251 ,  1.21848244, -2.2373541 ],
       [ 0.19456433,  0.80748367, -1.18596448,  1.82816806, -0.84204795],
       [ 0.61867902, -0.51722346,  0.72880629,  0.46438768, -0.75053521],
       [ 0.39198248, -0.28035204,  0.02500329, -0.07865188,  0.70449137]])

### randint

Returner tilfeldige heltall fra `lav` (inkludert) til` høy` (eksklusiv).

65

array([27, 34, 84, 98, 39, 27, 56, 62, 39, 56])

## Array Egenskaper og Metoder

La oss lære noen nyttige egenskaper og metoder en NumPy matrise har:

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([29, 48, 16, 13, 47, 38, 10, 40, 26, 19])

## Reshape

Returnerer en matrise som inneholder de samme dataene med en ny form.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Dette er nyttige metoder for å finne maks- eller minverdier. Eller for å finne indeksplasseringene deres ved hjelp av argmin eller argmax

array([29, 48, 16, 13, 47, 38, 10, 40, 26, 19])

48

1

10

6

## Shape

Shape er et egenskap som arrays har (ikke en metode):

(25,)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

(1, 25)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

(25, 1)

### dtype

Du kan også hente datatypen til objektet i matrisen:

dtype('int32')