# NumPy Indeksering og Valg

I denne notisboken vil vi lære hvordan du velger elementer eller grupper av elementer fra en matrise.

In [1]:
import numpy as np

c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Brakettindeksering og valg

Den enkleste måten å velge ett eller noen av elementene i en matrise ser veldig ut som pythonlister:

8

array([1, 2, 3, 4])

array([0, 1, 2, 3, 4])

## Kringkasting

Numpy arrays skiller seg fra en vanlig Python-liste på grunn av deres evne til å kringkaste:

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([0, 1, 2, 3, 4, 5])

array([99, 99, 99, 99, 99, 99])

Vær oppmerksom på at endringene også forekommer i vårt originale utvalg!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data blir ikke kopiert, det er en visning av den opprinnelige matrisen! Dette unngår minneproblemer!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indeksere et 2D-array (matriser)

Det generelle formatet er **arr_2d [rad] [kol]** eller **arr_2d [rad, kol]**. Jeg anbefaler vanligvis å bruke komma-notasjonen for klarhet.

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

array([20, 25, 30])

20

20

array([[10, 15],
       [25, 30]])

array([35, 40, 45])

array([35, 40, 45])

### Fancy indeksering

Fancy indeksering lar deg velge hele rader eller kolonner ute av rekkefølge, for å vise dette, la oss raskt bygge ut en nummer matrise:

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indeksering tillater følgende

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Valg

La oss kort gå over hvordan du bruker parenteser for valg basert på sammenligningsoperatører.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

array([ 5,  6,  7,  8,  9, 10])

array([ 3,  4,  5,  6,  7,  8,  9, 10])

array([ 3,  4,  5,  6,  7,  8,  9, 10])